=== P3trmat/Prehravac/petr_matousek.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Prehravac-nastaveni">
    <xs:annotation>
      <xs:documentation>Odkaz na Github: https://github.com/P3trmat/Prehravac.git</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hlavni"> <!-- Hlavní nastavení -->
          <xs:annotation>
            <xs:documentation>Hlavni</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="jazyk"/>
              <xs:element type="xs:byte" name="automaticky-aktualizovat"/>
              <xs:element name="vzhled-a-chovani">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="vzhled"/>
                    <xs:element type="xs:byte" name="povolit-vice-instanci"/>
                    <xs:element type="xs:byte" name="integrovat-video-do-rozhrani"/>
                    <xs:element type="xs:byte" name="posledni-pozice"/>
                    <xs:element name="po-ukonceni-prehravani">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="xs:Vypnout"/>
                          <xs:enumeration value="xs:Zastavit"/>
                          <xs:enumeration value="xs:Prehrat znovu"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="automaticky-pouzivat-pro-tyto-typy-souboru">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="mp3"/>
                    <xs:element type="xs:byte" name="mkv"/>
                    <xs:element type="xs:byte" name="mp4"/>
                    <xs:element type="xs:byte" name="avi"/>
                    <xs:element type="xs:byte" name="MPG"/>
                    <xs:element type="xs:byte" name="MPEG"/>
                    <xs:element type="xs:byte" name="FLAC"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:byte" name="zobrazit-ikonu-v-panelu"/>
              <xs:element type="xs:byte" name="resetovat-nastaveni"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element> <!-- Konec hlaví nastavení -->
        <xs:element name="Video"> <!-- Video -->
          <xs:annotation>
            <xs:documentation>Video</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="povolit-video"/>
              <xs:element name="obecne">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="vzdy-cela-obrazovka"/>
                    <xs:element type="xs:byte" name="nemenit-rozliseni-ve-fullscreen"/>
                    <xs:element type="xs:byte" name="vzdy-navrchu"/>
                    <xs:element type="xs:integer" name="rychlost-prehravani"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="zoom"/>
              <xs:element name="Barvy">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:integer" name="jas"/>
                    <xs:element type="xs:integer" name="kontrast"/>
                    <xs:element type="xs:integer" name="sytost"/>
                    <xs:element type="xs:integer" name="odstin"/>
                    <xs:element type="xs:byte" name="vychozi"/>
                    <xs:element type="xs:byte" name="pamatovat-si-nastaveni"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Obraz">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pomer-stran"/> <!-- Vyber poměru stran -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="xs:4:3"/>
                          <xs:enumeration value="xs:16:9"/>
                          <xs:enumeration value="xs:16:10"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="rozliseni"/> <!-- Vyber rozliseni -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="xs:1620x1080"/>
                          <xs:enumeration value="xs:800x600"/>
                          <xs:enumeration value="xs:1280x720"/>
                          <xs:enumeration value="xs:2048x1536"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:byte" name="oriznout-okraje"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>       <!-- konec video -->
        <xs:element name="Zvuk"> <!-- Zvuk -->
          <xs:annotation>
            <xs:documentation>Zvuk</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="povolit-zvuk"/>
              <xs:element name="hlasitost"/>    <!-- Omezení hlasitosti -->
              <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minclusive value="0"/>
                          <xs:maxclusive value="100"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
              <xs:element type="xs:byte" name="dolby-surround"/>
              <xs:element type="xs:byte" name="prostorovy-efekt-sluchatek"/>
              <xs:element type="xs:string" name="vystup"/>
              <xs:element type="xs:byte" name="vizualizace"/>
              <xs:element name="zvukova-stopa"/>      <!-- Vyber stopy -->
              <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="xs:stopa1"/>
                          <xs:enumeration value="xs:stopa2"/>
                          <xs:enumeration value="xs:stopa3"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
              <xs:element type="xs:integer" name="vyvazeni-L-P"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="titulky">
          <xs:annotation> <!-- Konec zvuk -->
            <xs:documentation>Titulky</xs:documentation>  <!-- Titulky -->
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="zakazat-titulky"/>
              <xs:element name="umisteni"/>
              <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="xs:dole uprostred"/>
                          <xs:enumeration value="xs:nahore uprostred"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
              <xs:element type="xs:integer" name="zpozdeni"/>
              <xs:element name="vlastnosti-primarnich-titulku">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="pismo"/>
                    <xs:element type="xs:integer" name="velikost"/>
                    <xs:element type="xs:string" name="barva-pisma"/>
                    <xs:element type="xs:string" name="barva-obrysu"/>
                    <xs:element type="xs:string" name="sirka-pozadi"/>
                    <xs:element type="xs:string" name="barva-pozadi"/>
                    <xs:element type="xs:string" name="pruhlednost-pozadi"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:byte" name="sekundarni-titulky"/>
              <xs:element name="vlastnosti-sekundarnich-titulku">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="pismo"/>
                    <xs:element type="xs:integer" name="velikost"/>
                    <xs:element type="xs:string" name="barva-pisma"/>
                    <xs:element type="xs:string" name="barva-obrysu"/>
                    <xs:element type="xs:string" name="sirka-pozadi"/>
                    <xs:element type="xs:string" name="barva-pozadi"/>
                    <xs:element type="xs:string" name="pruhlednost-pozadi"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>     <!-- konec Titulky -->

</xs:schema>

=== P3trmat/Prehravac/petr_matousek.xml
<?xml version="1.0" encoding="UTF-8"?> 
  <?xml-stylesheet type="text/xsl" href="petr_matousek.xsl"?>
  <!-- Odkaz na github: https://github.com/P3trmat/Prehravac.git --> 
<Prehravac-nastaveni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="petr_matousek.xsd">

<!-- Hlavni nastavenÃ­ -->
<hlavni>
		<jazyk>CZ</jazyk>
	<automaticky-aktualizovat>0</automaticky-aktualizovat>
	<vzhled-a-chovani>
    <vzhled>Vychozi</vzhled>
		<povolit-vice-instanci>0</povolit-vice-instanci>
		<integrovat-video-do-rozhrani>1</integrovat-video-do-rozhrani>
		<posledni-pozice>1</posledni-pozice>
    <po-ukonceni-prehravani>Vypnout</po-ukonceni-prehravani>
	</vzhled-a-chovani>
  <automaticky-pouzivat-pro-tyto-typy-souboru>
    <mp3>1</mp3>
    <mkv>1</mkv>
    <mp4>1</mp4>
    <avi>1</avi>
    <MPG>1</MPG>
    <MPEG>1</MPEG>
    <FLAC>1</FLAC>
  </automaticky-pouzivat-pro-tyto-typy-souboru>
	<zobrazit-ikonu-v-panelu>1</zobrazit-ikonu-v-panelu>
	<resetovat-nastaveni>0</resetovat-nastaveni>	
	
</hlavni>

<!-- Video -->
<Video>
  <povolit-video>1</povolit-video>
  <obecne>
	 <vzdy-cela-obrazovka>0</vzdy-cela-obrazovka>
	 <nemenit-rozliseni-ve-fullscreen>1</nemenit-rozliseni-ve-fullscreen>
	 <vzdy-navrchu>1</vzdy-navrchu>
	 <rychlost-prehravani>1</rychlost-prehravani>
  </obecne>
	<zoom>100%</zoom>
	<Barvy>
		<jas>2</jas>
		<kontrast>1</kontrast>
		<sytost>0</sytost>
		<odstin>1</odstin>
		<vychozi>0</vychozi>
		<pamatovat-si-nastaveni>0</pamatovat-si-nastaveni>
	</Barvy>
	<Obraz>
		<pomer-stran>16:9</pomer-stran>
		<rozliseni>1920x1080</rozliseni>
		<oriznout-okraje>0</oriznout-okraje>
	</Obraz>
</Video>

<!-- Zvuk -->
  <Zvuk>
  	<povolit-zvuk>1</povolit-zvuk>
  	<hlasitost>50</hlasitost>
  	<dolby-surround>1</dolby-surround>
  	<prostorovy-efekt-sluchatek>1</prostorovy-efekt-sluchatek>
  	<vystup>Reproduktory</vystup>
  	<vizualizace>0</vizualizace>
  	<zvukova-stopa>stopa 1</zvukova-stopa>
  	<vyvazeni-L-P>50</vyvazeni-L-P>
  </Zvuk>

  <!-- Titulky -->
  <titulky>
  	<zakazat-titulky>0</zakazat-titulky>
  	<umisteni>dole uprostred</umisteni>
  	<zpozdeni>0</zpozdeni>
  	<vlastnosti-primarnich-titulku>
  			<pismo>Aerial</pismo>
  			<velikost>30</velikost>
  			<barva-pisma>bila</barva-pisma>
        <barva-obrysu>cerna</barva-obrysu>
        <sirka-pozadi>Normalni</sirka-pozadi>
  			<barva-pozadi>cerna</barva-pozadi>
        <pruhlednost-pozadi>100%</pruhlednost-pozadi>
  	</vlastnosti-primarnich-titulku>
    <sekundarni-titulky>0</sekundarni-titulky>
    <vlastnosti-sekundarnich-titulku>
        <pismo>Aerial</pismo>
        <velikost>15</velikost>
        <barva-pisma>zluta</barva-pisma>
        <barva-obrysu>cerna</barva-obrysu>
        <sirka-obrysu>Normalni</sirka-obrysu>
        <barva-pozadi>cerna</barva-pozadi>
        <pruhlednost-pozadi>100%</pruhlednost-pozadi>
    </vlastnosti-sekundarnich-titulku>
  </titulky>
</Prehravac-nastaveni>
